### ISSUE TITLE
How to change tooltip using RN?

### ISSUE THREAD

**Issue by vinirk** [aloneszjl/react-native-f2chart#22]
Hey all,

I'm using the chart on RN project.
I want to know how can I custom my tooltip. I saw we have a prop called onChange, but I do not know what I need to do.
If someone could send an example, I will appreciate.

Thanks.

**Comment by vinirk** [comment]
Hey guys,

I closed this issue, because I got it how to use it. Actually the onChange method It's just to debug and check what's It's coming from the graph API.

A good idea would be a prop where we could pass our component styled and formatted.

Thanks

**Comment by GuleriaAshish** [comment]
Did you find any solution of how to use onChange?
